POST http://localhost:3000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.amazon.in/BATA-Womens-Fashion-Sandals-6-6617915/dp/B07W8YBR9W/?_encoding=UTF8&pd_rd_w=P3rc0&content-id=amzn1.sym.1f592895-6b7a-4b03-9d72-1a40ea8fbeca&pf_rd_p=1f592895-6b7a-4b03-9d72-1a40ea8fbeca&pf_rd_r=EW0YFAPRDF10916N5G3G&pd_rd_wg=vm7CU&pd_rd_r=32f35c96-4889-4fdd-9e15-0d66f1138a03&ref_=pd_gw_ci_mcx_mr_hp_atf_m"
}